// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA105Ubo_zpO7zwUgu__Eq_kSCvB0hrTBA',
    appId: '1:387135180117:web:21a14fb364445b625d33dc',
    messagingSenderId: '387135180117',
    projectId: 'investment-manager-4c55c',
    authDomain: 'investment-manager-4c55c.firebaseapp.com',
    storageBucket: 'investment-manager-4c55c.appspot.com',
    measurementId: 'G-31P099478Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnlIKQMSfxdzubZLEyaNEjlnGkTpgPHnY',
    appId: '1:387135180117:android:3a5e47629cbb0bc05d33dc',
    messagingSenderId: '387135180117',
    projectId: 'investment-manager-4c55c',
    storageBucket: 'investment-manager-4c55c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbjmeo7Fy51aHlyki6IlYBTHOS5niRdb8',
    appId: '1:387135180117:ios:cb692c8447bfac3a5d33dc',
    messagingSenderId: '387135180117',
    projectId: 'investment-manager-4c55c',
    storageBucket: 'investment-manager-4c55c.appspot.com',
    iosBundleId: 'com.example.investmentManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbjmeo7Fy51aHlyki6IlYBTHOS5niRdb8',
    appId: '1:387135180117:ios:d848f8abbcaabadb5d33dc',
    messagingSenderId: '387135180117',
    projectId: 'investment-manager-4c55c',
    storageBucket: 'investment-manager-4c55c.appspot.com',
    iosBundleId: 'com.example.investmentManager.RunnerTests',
  );
}
